{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-3498", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:30 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-03-20", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/106453", "Description": "BID:106453"}, {"URL": "https://www.debian.org/security/2019/dsa-4363", "Description": "DEBIAN:DSA-4363"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/", "Description": "FEDORA:FEDORA-2019-5ad2149e99"}, {"URL": "https://docs.djangoproject.com/en/dev/releases/security/", "Description": "MISC:https://docs.djangoproject.com/en/dev/releases/security/"}, {"URL": "https://groups.google.com/forum/#%21topic/django-announce/VYU7xQQTEPQ", "Description": "MISC:https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ"}, {"URL": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/", "Description": "MISC:https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html", "Description": "MLIST:[debian-lts-announce] 20190106 [SECURITY] [DLA 1629-1] python-django security update"}, {"URL": "https://usn.ubuntu.com/3851-1/", "Description": "UBUNTU:USN-3851-1"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-01-09"}