{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-13095", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in fs/xfs/libxfs/xfs_inode_buf.c in the Linux kernel through 4.17.3. A denial of service (memory corruption and BUG) can occur for a corrupted xfs image upon encountering an inode that is in extent format, but has more extents than fit in the inode fork.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:22 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-08-06", "cve_detail": "", "references": [{"URL": "https://bugzilla.kernel.org/show_bug.cgi?id=199915", "Description": "MISC:https://bugzilla.kernel.org/show_bug.cgi?id=199915"}, {"URL": "https://git.kernel.org/pub/scm/fs/xfs/xfs-linux.git/commit/?h=for-next&id=23fcb3340d033d9f081e21e6c12c2db7eaa541d3", "Description": "MISC:https://git.kernel.org/pub/scm/fs/xfs/xfs-linux.git/commit/?h=for-next&id=23fcb3340d033d9f081e21e6c12c2db7eaa541d3"}, {"URL": "https://github.com/torvalds/linux/commit/23fcb3340d033d9f081e21e6c12c2db7eaa541d3", "Description": "MISC:https://github.com/torvalds/linux/commit/23fcb3340d033d9f081e21e6c12c2db7eaa541d3"}, {"URL": "https://access.redhat.com/errata/RHSA-2019:1350", "Description": "REDHAT:RHSA-2019:1350"}, {"URL": "https://access.redhat.com/errata/RHSA-2019:2029", "Description": "REDHAT:RHSA-2019:2029"}, {"URL": "https://access.redhat.com/errata/RHSA-2019:2043", "Description": "REDHAT:RHSA-2019:2043"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-07-03"}