{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-12563", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in Linaro LAVA before 2018.5.post1. Because of support for file: URLs, a user can force lava-server-gunicorn to download any file from the filesystem if it's readable by lavaserver and valid yaml.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:20 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-06-19", "cve_detail": "", "references": [{"URL": "https://git.linaro.org/lava/lava.git/commit/?id=e24ec39599bc07562ad8bc2a581144b8448cb214", "Description": "CONFIRM:https://git.linaro.org/lava/lava.git/commit/?id=e24ec39599bc07562ad8bc2a581144b8448cb214"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-06-19"}