{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-16438", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:34 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-09-03", "cve_detail": "", "references": [{"URL": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat", "Description": "MISC:https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-09-03"}