{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-10930", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "A flaw was found in RPC request using gfs3_rename_req in glusterfs server. An authenticated attacker could use this flaw to write to a destination outside the gluster volume.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:15 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-04-02", "cve_detail": "", "references": [{"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10930", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10930"}, {"URL": "https://review.gluster.org/#/c/glusterfs/+/21068/", "Description": "CONFIRM:https://review.gluster.org/#/c/glusterfs/+/21068/"}, {"URL": "https://security.gentoo.org/glsa/201904-06", "Description": "GENTOO:GLSA-201904-06"}, {"URL": "https://lists.debian.org/debian-lts-announce/2018/09/msg00021.html", "Description": "MLIST:[debian-lts-announce] 20180920 [SECURITY] [DLA 1510-1] glusterfs security update"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:2607", "Description": "REDHAT:RHSA-2018:2607"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:2608", "Description": "REDHAT:RHSA-2018:2608"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:3470", "Description": "REDHAT:RHSA-2018:3470"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-09-04"}