{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-10879", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:15 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-02-09", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/104902", "Description": "BID:104902"}, {"URL": "http://patchwork.ozlabs.org/patch/928666/", "Description": "CONFIRM:http://patchwork.ozlabs.org/patch/928666/"}, {"URL": "http://patchwork.ozlabs.org/patch/928667/", "Description": "CONFIRM:http://patchwork.ozlabs.org/patch/928667/"}, {"URL": "https://bugzilla.kernel.org/show_bug.cgi?id=200001", "Description": "CONFIRM:https://bugzilla.kernel.org/show_bug.cgi?id=200001"}, {"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879"}, {"URL": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=513f86d73855ce556ea9522b6bfd79f87356dc3a", "Description": "CONFIRM:https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=513f86d73855ce556ea9522b6bfd79f87356dc3a"}, {"URL": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5369a762c882c0b6e9599e4ebbb3a9ba9eee7e2d", "Description": "CONFIRM:https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5369a762c882c0b6e9599e4ebbb3a9ba9eee7e2d"}, {"URL": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html", "Description": "MLIST:[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:2948", "Description": "REDHAT:RHSA-2018:2948"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:3083", "Description": "REDHAT:RHSA-2018:3083"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:3096", "Description": "REDHAT:RHSA-2018:3096"}, {"URL": "https://usn.ubuntu.com/3753-1/", "Description": "UBUNTU:USN-3753-1"}, {"URL": "https://usn.ubuntu.com/3753-2/", "Description": "UBUNTU:USN-3753-2"}, {"URL": "https://usn.ubuntu.com/3871-1/", "Description": "UBUNTU:USN-3871-1"}, {"URL": "https://usn.ubuntu.com/3871-3/", "Description": "UBUNTU:USN-3871-3"}, {"URL": "https://usn.ubuntu.com/3871-4/", "Description": "UBUNTU:USN-3871-4"}, {"URL": "https://usn.ubuntu.com/3871-5/", "Description": "UBUNTU:USN-3871-5"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-07-26"}