{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-1112", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "glusterfs server before versions 3.10.12, 4.0.2 is vulnerable when using 'auth.allow' option which allows any unauthenticated gluster client to connect from any network to mount gluster storage volumes. NOTE: this vulnerability exists because of a CVE-2018-1088 regression.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:15 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-05-01", "cve_detail": "", "references": [{"URL": "https://access.redhat.com/articles/3422521", "Description": "CONFIRM:https://access.redhat.com/articles/3422521"}, {"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1112", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1112"}, {"URL": "https://review.gluster.org/#/c/19899/1..2", "Description": "CONFIRM:https://review.gluster.org/#/c/19899/1..2"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:1268", "Description": "REDHAT:RHSA-2018:1268"}, {"URL": "https://access.redhat.com/errata/RHSA-2018:1269", "Description": "REDHAT:RHSA-2018:1269"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-04-25"}