{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2016-9394", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "The jas_seq2d_create function in jas_seq.c in JasPer before 1.900.17 allows remote attackers to cause a denial of service (assertion failure) via a crafted file.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:01:52 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-06-28", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/94372", "Description": "BID:94372"}, {"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1396975", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=1396975"}, {"URL": "https://github.com/mdadams/jasper/commit/f7038068550fba0e41e1d0c355787f1dcd5bf330", "Description": "CONFIRM:https://github.com/mdadams/jasper/commit/f7038068550fba0e41e1d0c355787f1dcd5bf330"}, {"URL": "https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure", "Description": "MISC:https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure"}, {"URL": "http://www.openwall.com/lists/oss-security/2016/11/17/1", "Description": "MLIST:[oss-security] 20161117 Re: jasper: multiple assertion failures"}, {"URL": "https://access.redhat.com/errata/RHSA-2017:1208", "Description": "REDHAT:RHSA-2017:1208"}, {"URL": "https://usn.ubuntu.com/3693-1/", "Description": "UBUNTU:USN-3693-1"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-03-23"}